### ISSUE TITLE
Permissions Abuses

### ISSUE THREAD

**Issue by Geedy** [Banbeucmas/MCVNDiscord-Server#27]
Nesfan abusing refund permissions to get bedrock + machines that shop don't sell and attempt to sell to other players to get money, unfair issue please fix.
Proof: https://imgur.com/a/3Mk89q2
        - https://imgur.com/a/OoxTBII

**Comment by n3sfan** [comment]
cuz banbeucmas doesn't sell lol

**Comment by n3sfan** [comment]
đặt nào bệu

**Comment by n3sfan** [comment]
btw i'm sorry just for testing and fun

**Comment by thanhgay03** [comment]
idk

**Comment by Kinue72** [comment]
idk

**Comment by Banbeucmas** [comment]
https://github.com/Banbeucmas/MCVNDiscord-Server/issues/10
Xong cái này thì tự khắc có
