### ISSUE TITLE
Dịch DiscordSRV

### ISSUE THREAD

**Issue by Banbeucmas** [Banbeucmas/MCVNDiscord-Server#3]
Thằng nào rảnh đời dịch hộ em cái này... Em lười lắm...

**Comment by Banbeucmas** [comment]
https://github.com/Banbeucmas/MCVNDiscord-Server/blob/master/plugins/DiscordSRV/messages.yml
Đã chỉnh lại .gitignore cho phù hợp

**Comment by letruongthinh** [comment]
dịch xong r merge đi dume

**Comment by letruongthinh** [comment]
close cái issue này lun

**Comment by Banbeucmas** [comment]
Cứ để đó, t sẽ merge

**Comment by Banbeucmas** [comment]
https://github.com/Banbeucmas/MCVNDiscord-Server/pull/5
Xử lý xong, closed
